mini_hackathone/mini_hackathone/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from dongnechaekbang import views
import dongnechaekbang.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',dongnechaekbang.views.home, name='home'),
    path('location/', views.location, name="location"),
    path('location/<int:bookstore_id>', views.location_bookstore, name="bookstore"),
    path('search/',dongnechaekbang.views.search, name='search'),
    path('search/result/',dongnechaekbang.views.result, name='result'),
    path('community',dongnechaekbang.views.community.as_view(), name='community'),
    path('community_view<pk>',dongnechaekbang.views.community_view.as_view(),name="community_view"),
    path('community_delete/<pk>',dongnechaekbang.views.community_delete.as_view(),name="community_delete"),
    path('community_update/<pk>',dongnechaekbang.views.community_update.as_view(),name="community_update"),
    path('community_write',dongnechaekbang.views.community_write.as_view(),name='community_write'),
    path('comment_write/<int:pk>',dongnechaekbang.views.comment_write,name='comment_write'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mini_hackathone/dongnechaekbang/models.py
from django.utils import timezone
from django.db import models
from django.conf import settings

# Create your models here.

class Blog(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=100)
    text = models.TextField(max_length=2000)
    author = models.CharField(max_length=100)
    time = models.DateTimeField(default=timezone.now)
    hit = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.title

    @property
    def update_counter(self):
        self.hit = self.hit +1
        self.save()

class Comment(models.Model):
    objects = models.Manager()
    post=models.ForeignKey(Blog, on_delete=models.CASCADE, null=True, related_name='comments')
    comment_date=models.DateTimeField(default=timezone.now)
    comment_contents=models.CharField(max_length=200)
    comment_writer=models.CharField(max_length=100)

class Trait(models.Model):
    objects = models.Manager()
    traits = models.CharField(max_length=50, primary_key=True) # manager can categorize traits of abstract mood
    def __str__(self):
        return self.traits

class Bookstore(models.Model):
    objects = models.Manager()
    name = models.CharField(max_length=20, default="d", null=True) # name of bookstore
    city_address_of_bookstore = models.CharField(max_length=20) # location of bookstore in city scale
    specific_address = models.TextField() # location of bookstore in specific scale
    trait = models.ForeignKey(Trait, on_delete=models.CASCADE)# trait of bookstore
    bookstore_information = models.TextField() # summary about bookstore
    bookstore_image = models.ImageField(upload_to="image", blank=True)
    def __str__(self):
        return self.name
    
class Evaluation_about_bookstore(models.Model):
    objects = models.Manager()
    evaluation = models.IntegerField(default=0) # about evaluations, mark with number 1 to 5
    comment_about_bookstore_with_text = models.TextField() # utility of comments, user can evaluate with text
    #comment_about_bookstore_with_image = models.ImageField(upload_to="image", blank=True) # utility of comments, user can upload image


class Informations(models.Model):
    objects = models.Manager()
    bookstore = models.ForeignKey(Bookstore, on_delete=models.CASCADE)
    bookstore_image = models.ImageField(upload_to="image", blank=True) # relevant image of bookstore


class Bookstore_event(models.Model):
    objects = models.Manager()
    event_name = models.CharField(max_length=20) # name of events
    event_date = models.DateField(auto_now=True) # date of events
    bookstore = models.ForeignKey(Bookstore, on_delete=models.CASCADE) # bookstore where it be

    # bookstore_resrvation = models.ForeignKey(user, on_delete = models.SET_NULL, null=True, blank=True) # utility of who resrvate bookstore // it is not work

mini_hackathone/dongnechaekbang/forms.py
from django import forms

class upload_photo(forms.Form):
    photo = forms.ImageField(label="photo")

mini_hackathone/dongnechaekbang/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Blog, Bookstore, Evaluation_about_bookstore, Informations
# import model data
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.db.models import Q

# Create your views here.

def home(request):
    return render(request, 'home.html')

def location(request):
    bookstore_model = Bookstore.objects.all()
    evaluation_about_bookstore_model = Evaluation_about_bookstore.objects.all()
    informations_model = Informations.objects.all()
    # insert model information to use in location.html

    context = {
        'bookstore' : bookstore_model, 
        'evaluation_about_bookstore' : evaluation_about_bookstore_model, 
        'informations' : informations_model, 
    }
    # declare variable
    
    return render(request, 'location.html', context)

def location_bookstore(request, bookstore_id):

    bookstore = get_object_or_404(Bookstore, pk=bookstore_id)
    bookstore_model = Bookstore.objects.all()
    # insert model information to use in location_bookstore.html

    """ city_address_of_bookstore_을지로_model = bookstore_model.filter(city_address_of_bookstore='을지로')
    city_address_of_bookstore_망원동_model = bookstore_model.filter(city_address_of_bookstore='망원동')
    # to list city address of bookstore """
    # 사용 안합니다

    context = {
        'bookstores' : bookstore, 
        'bookstore' : bookstore_model
    }
    # declare variable

    return render(request, 'location_bookstore.html', context)

def search(request):
    return render(request, 'search.html')

def result(request):
    bookstoreinfo = Bookstore.objects.all()
    query = request.GET.get('query','') 
    search_type = request.GET.get('type','')
    if query:
        if search_type == 'all':
            bookstoreinfo = bookstoreinfo.filter(Q(name__icontains=query)| Q(city_address_of_bookstore__icontains=query) | Q(trait__icontains=query)|Q(bookstore_information__icontains=query))
        elif search_type == 'name':
            bookstoreinfo = bookstoreinfo.filter(name__icontains=query)
        elif search_type == 'city_address_of_bookstore':
            bookstoreinfo = bookstoreinfo.filter(city_address_of_bookstore__icontains=query)
        elif search_type == 'trait':
            bookstoreinfo = bookstoreinfo.filter(trait__icontains=query)
        elif search_type == 'bookstore_information':
            bookstoreinfo = bookstoreinfo.filter(bookstore_information__icontains=query)
    return render(request, 'result.html',{'bookstoreinfo':bookstoreinfo , 'query':query})

class community(ListView):
    template_name = 'community.html'
    context_object_name = 'blog_list' 
    def get_queryset(self):
        return Blog.objects.all

class community_view(DetailView):
    model = Blog
    template_name = 'community_view.html'
    context_object_name = 'blog'

class community_delete(DeleteView):
    model = Blog
    template_name = 'community_delete.html'
    context_object_name = 'blog'
    success_url = reverse_lazy('community')

class community_update(UpdateView):
    model = Blog
    template_name = 'community_update.html'
    fields = ['title','text']
    success_url = reverse_lazy('community')

class community_write(CreateView):
    model=Blog
    template_name='community_write.html'
    fields=['title','text']

    def form_valid(self,form):
        Blog=form.save(commit=False)
        Blog.author=self.request.user
        Blog.save()

        return HttpResponseRedirect(self.request.POST.get('next','/'))

def comment_write(request, post_pk):
    if request.method == 'POST':
        post=get_object_or_404(Blog, pk=post_pk)
        content=request.POST.get('comment_contents')
        context = {
            'post_pk' : post_pk
        }

        Comment.objects.create(post=post, comment_write=writer,comment_contents=content)
        return HttpResponseRedirect(reverse_lazy('community', context))

mini_hackathone/dongnechaekbang/templates/community.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1 class="intro-title mb-4"><center>골목책방</center></h1>
	팀원 : 김진우 김지은 정지원  <br><br><br>

	전국 곳곳에 있는 독립 서점들의 위치 및 정보를 취합하고, 일반인들이 쉽게 접할 수 없는 독립서적에 대한 정보를 알기 쉽게 정리하여 공유한다.<br><br><br>

	의도한 기능 1 - 홈 : 해당 서비스의 이름인 '골목책방'의 이름을 보여주고, 서비스의 제공 목적을 압축적으로 정리한 '독서, 그 이상의 가치' 문구를 삽입하여 서비스에 대한 이해를 높였다.<br><br>

	의도한 기능 2 - 위치 : 서비스 하는 서점들의 목록들과 해당 서점들의 위치와 같은 서점들의 대략적인 정보를 게시한다.<br><br>

	의도한 기능 3 - 검색 데이터베이스 내의 데이터들을 위치 데이터베이스와 연동시켜 좀 더 유기적으로 페이지를 옮겨 가며 정보를 제공할 수 있도록 의도함 <br><br>

	의도한 기능 4 - 검색 : 원하는 서적 혹은 서점을 검색하여 정제된 정보를 제공한다.<br><br>

	타겟 소비자 : 독립서점을 자주 애용하는 소비자들이 주 타겟이 될 것이며, 앞으로 해당 서점들을 이용할 소비자 층을 늘려나갈 것을 지향하고 있다.<br><br><br>

	아쉬운 점 :<br><br>
	1) 커뮤니티 서비스를 구현하려고 하였으나, 역량 부족 및 시간 부족으로 인해 구현하지 못했다.<br><br>
	2) 기능간의 이동을 하기 위해서는 홈으로 돌아가서 기능별로 진입해야 하는 불편함이 있다.<br><br>
	3) 아이디어를 확정 하고 발전 시키는 과정에서 우리가 의도한 서비스가 이미 배포 되어 사용되고 있는 것을 뒤늦게 발견하여 아쉬웠다.<br><br>
	4) 위치 기능 구현시 네이버 지도와 연결시키고자 했으나 능력부족으로 구현 실패하였다.<br><br>
	5) 검색을 하면 모든 내용이 검색결과로 노출되는 문제가 존재한다.


</body>
</html>

mini_hackathone/dongnechaekbang/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>mini_hackathone</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <link href="../static/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="../static/lib/animate/animate.min.css" rel="stylesheet">

  <link href="../static/style.css" rel="stylesheet">
</head>

<body id="page-top">

  <!--/ Nav Star /-->
  <nav class="navbar navbar-b navbar-trans navbar-expand-md fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll" href="#page-top">Independent Bookstore</a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault"
        aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <div class="navbar-collapse collapse justify-content-end" id="navbarDefault">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll active" href="#home">홈</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'location' %}">위치</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'search' %}">검색</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'community' %}">우리에 대하여</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!--/ Nav End /-->

  <!--/ Intro Skew Star /-->
  <div id="home" class="intro route bg-image" style="background-image: url(../static/img/bookstore.jpeg)">
    <div class="overlay-itro"></div>
    <div class="intro-content display-table">
      <div class="table-cell">
        <div class="container">
          <h1 class="intro-title mb-4">골목책방</h1>
          <p class="intro-subtitle"><span class="text-slider-items">독서, 그 이상의 가치</span><strong class="text-slider"></strong></p>
        </div>
      </div>
    </div>
  </div>

  <section id="location" class="about-mf sect-pt4 route"></section>
  <section id="search" class="services-mf route"></section>
  <section id="community" class="portfolio-mf sect-pt4 route"></section>


  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <div id="preloader"></div>

  <!-- JavaScript Libraries -->
  <script src="../static/lib/jquery/jquery.min.js"></script>
  <script src="../static/lib/jquery/jquery-migrate.min.js"></script>
  <script src="../static/lib/popper/popper.min.js"></script>
  <script src="../static/lib/bootstrap/js/bootstrap.min.js"></script>
  <script src="../static/lib/easing/easing.min.js"></script>
  <script src="../static/lib/counterup/jquery.waypoints.min.js"></script>
  <script src="../static/lib/counterup/jquery.counterup.js"></script>
  <script src="../static/lib/owlcarousel/owl.carousel.min.js"></script>
  <script src="../static/lib/lightbox/js/lightbox.min.js"></script>
  <script src="../static/lib/typed/typed.min.js"></script>
  <!-- Contact Form JavaScript File -->
  <script src="../static/contactform/contactform.js"></script>

  <!-- Template Main Javascript File -->
  <script src="../static/js/main.js"></script>

</body>
</html>

mini_hackathone/dongnechaekbang/templates/location.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = "stylesheet" type="text/css" href="../static/location.css">
    <title>Independent Book Store</title>
</head>
<body>
    <div class="container"><br>
        <ul class="navbar">
            <li class="title">
                <h1>동네책방과 함께하는 서점들</h1>
            </li>
            <li class="move_navbar">
                <span href="#">HoME</span>
            </li>
        </ul>
        <br><br><br><br>
        <div class="content">
            {% for bookstore_list in bookstore %}
            <div class="bookstore">
                <a href="{% url 'bookstore' bookstore_list.id %}">{{bookstore_list.name}}</a>
            </div>
            <br><br><br><br>
            {% endfor %}
        </div>
    </div>
</body>
</html>

mini_hackathone/dongnechaekbang/templates/location_bookstore.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = "stylesheet" type="text/css" href="../static/location_bookstore.css">
    <title>Independent Book Store</title>
</head>
<body>
    <div class="all_page">
        <div class="top_and_bottom_background"></div>
        <div class="middle_table">
            <div class="side_background"></div>
            <div class="container">
                <div class="title">
                    
                </div>
                <div class="picture_section">
                    <div class="picture">
                        <img src="{{bookstores.bookstore_image.url}}" height="300px" width="300px">
                    </div>
                </div>
                <div class="information_section">
                    <div class="book_store_name">
                        {{bookstores.name}}
                    </div>
                    <div class="book_store_traits">
                        {{bookstores.trait}}
                    </div>
                    <div class="book_store_specific_address">
                        {{bookstores.specific_address}}
                    </div>
                    <div class="book_store_informations">
                        {{bookstores.bookstore_information}}
                    </div>
                </div>
            </div>
            <div class="background"></div>
        </div>
        <div class="top_and_bottom_background"></div>
    </div>
</body>
</html>

mini_hackathone/dongnechaekbang/templates/result.html
{% load static %}
    
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> SEARCH RESULT </title>
    <link rel='stylesheet' href="{% static 'result.css' %}">
</head>
<body>
     <div class='container'>
         <div class='headbox'>
            <div class='homebox'>
                <a href="{% url 'search' %}"> HoME </a>
            </div>
            <div class='logo'>
                <a href="{% url 'search' %}"> 골목책방 </a>
                <div class="searchbox">
                <form action = "{% url 'result' %}" method = 'GET' >
                    <div class="selectbox">
                        <select id=type>
                            <option value="all">전체 </option>
                            <option value="name">서점</option>
                            <option value="city_address_of_bookstore">지역</option>
                            <option value="bookstore_information">서점 정보</option>
                            <option value="trait">책 이름</option>
                        </select>
                    </div>
                    <input class="input_box" type="text" name="query" value="{{query}}" placeholder=" 검색어를 입력해주세요 !">
                    <button id="imgbutton" type="submit" value=""> 검색 </button>
                </form>
                </div>
     
            </div>
         </div>

         <div class="contentbox">
             <div class="searchhead">
                "{{query}}"에 대한 결과는 다음과 같습니다.
             </div>
             <br>
            <div class="displayblock">
                {% for post in bookstoreinfo %}
                <div class='searchresult'>
                <div class='list'> <img src="{{post.bookstore_image.url}}" width="130px" height="100px"> &nbsp; &nbsp; </div>
                <div class='list2'> <h3>서점 이름:</h3> <p> {{post.name}}</p>  &nbsp;  &nbsp; </div>
                <div class='list2'> <h3>지역:</h3> <p> {{post.city_address_of_bookstore}}</p>  &nbsp;  &nbsp; </div>
                <a id="more" href="{{'#'}}"> <img src="https://user-images.githubusercontent.com/63120934/89040290-7fb30480-d37e-11ea-8ae3-c18c59c39adf.png" width="30px" height="30px"> </a>
                </div>
                {% endfor %}  
            </div>
         </div>
     </div>
</body>
</html>

mini_hackathone/dongnechaekbang/templates/search.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> SEARCH </title>
    <link rel='stylesheet' href="{% static 'search.css' %}" >
</head>
<body>
    <div class="container">
        <div class='headbox'>
            <div class='logo'>
                <a href="{% url 'search' %}"> 골목책방 </a>
            </div>
            <div class='homebox'>
                <a href="{% url 'search' %}"> HoME </a>
            </div>
        </div>
        <div class='searchbox'>
            <form action = "{% url 'result' %}" method = 'GET' >
                <div class="selectbox">
                    <select id=type>
                        <option value="all">전체 </option>
                        <option value="name">서점</option>
                        <option value="city_address_of_bookstore">지역</option>
                        <option value="bookstore_information">서점 정보</option>
                        <option value="trait">책 이름</option>
                    </select>
                </div>
                <input class="input_box" type="text" name="query" value="{{query}}" placeholder=" 검색어를 입력해주세요 !">
                <button id="imgbutton" type="submit" value=""> 검색 </button>
            </form>
        </div>
    </div>
</body>
</html>